### ISSUE TITLE
Steam Deck

### ISSUE THREAD

**Issue by DylanTackoor** [Venomalia/UniversalDynamicInput#108]
### Input device?

Steam Deck

### Input device ID?

evdev/0/Valve Software Steam Deck Controller

### Operating System?

SteamOS 3

### What is the key assignment.

[`GCpadNew.ini`](https://github.com/dragoonDorise/EmuDeck/blob/main/configs/org.DolphinEmu.dolphin-emu/config/dolphin-emu/GCPadNew.ini) as configured by EmuDeck

```
[GCPad1]
Device = evdev/0/Microsoft X-Box 360 pad 0
Buttons/A = SOUTH
Buttons/B = EAST
Buttons/X = NORTH
Buttons/Y = WEST
Buttons/Z = TR
Buttons/Start = START
Main Stick/Up = `Axis 1-`
Main Stick/Down = `Axis 1+`
Main Stick/Left = `Axis 0-`
Main Stick/Right = `Axis 0+`
Main Stick/Modifier = `Shift`
Main Stick/Modifier/Range = 50.000000000000000
Main Stick/Calibration = 100.00 101.96 105.46 110.28 110.96 106.32 102.08 101.92 100.00 101.96 106.04 112.82 112.69 106.81 101.42 100.21 100.00 101.96 107.34 112.09 115.31 115.88 108.24 101.96 99.54 99.80 104.07 106.47 107.28 110.92 105.35 101.96
C-Stick/Up = `Axis 4-`
C-Stick/Down = `Axis 4+`
C-Stick/Left = `Axis 3-`
C-Stick/Right = `Axis 3+`
C-Stick/Modifier = `Ctrl`
C-Stick/Modifier/Range = 50.000000000000000
C-Stick/Calibration = 100.00 101.96 108.24 112.25 112.76 111.88 108.24 101.96 100.00 98.55 97.64 100.59 107.99 110.64 108.24 101.96 100.00 101.96 106.57 115.58 118.40 116.73 108.24 101.96 100.00 101.96 105.64 105.39 107.99 111.37 107.46 101.96
Triggers/L = `Full Axis 2+`
Triggers/R = `Full Axis 5+`
D-Pad/Up = `Axis 7-`
D-Pad/Down = `Axis 7+`
D-Pad/Left = `Axis 6-`
D-Pad/Right = `Axis 6+`
Triggers/L-Analog = `Full Axis 2+`
Triggers/R-Analog = `Full Axis 5+`
Rumble/Motor = Strong
```

**Comment by DylanTackoor** [comment]
hah just realized the key assignment is invalid as it's not for the `evdev/0/Valve Software Steam Deck Controller` 🤦 I'll try getting a proper config for it

**Comment by DylanTackoor** [comment]
I could only get the `evdev/0/Microsoft X-Box 360 pad 0` to work ☹️

**Comment by Venomalia** [comment]
I can't do much with config files, so how should I know what the e.g. R3 or select button is?
I need them in a format `key id = key description`.
please use the linked templates https://github.com/Venomalia/UniversalDynamicInput/wiki/Device-Templates#evdev,

**Comment by Venomalia** [comment]
By the way, are you using EmuDeck?
Mine that there not used the official Dolphin version, which may cause problems.

**Comment by DylanTackoor** [comment]
@Venomalia yeah I'm using the [Dolphin flatpak](https://github.com/flathub/org.DolphinEmu.dolphin-emu) that EmuDeck installs. I'll [try compiling it](https://wiki.dolphin-emu.org/index.php?title=Building_Dolphin_on_Linux#General_purpose_script) later to see if that will get the `evdev/0/Valve Software Steam Deck Controller` to respond in Dolphin 🤷

**Comment by RazorDarkAMG** [comment]
What version is it ? Thank's !

**Comment by megasart** [comment]
When I load this into prime trilogy the textures load upside down
