### ISSUE TITLE
[Device Rquest] - Logitech F710

### ISSUE THREAD

**Issue by ChristianSilvermoon** [Venomalia/UniversalDynamicInput#114]
### Input device?

Logitech F710

### Input device ID?

SDL/0/Logitech Gamepad F710

### Operating System?

Linux

### What is the key assignment.

Input in Dolphin | Physical Inputs on Controller
:-: | :-:
`Button 0` | A
`Button 1` | B
`Button 2` | X
`Button 3` | Y
`Button 4` | LB
`Button 5` | RB
`Button 6` | Back
`Button 7` | Start
`Button 8` | Guide (Logitech Button)
`Button 9` | Left Stick, Press/Click
`Button 10` | Right Stick, Press/Click
`Hat 0 N` | D-Pad Up
`Hat 0 E` | D-Pad Right
`Hat 0 S` | D-Pad Down
`Hat 0 W` | D-Pad Left
`Axis 0-` | Left Stick, left
`Axis 0+` | Left Stick, right
`Full Axis 0-` | Left Stick, left
`Full Axis 0+` | Left Stick, right
`Axis 1-` | Left Stick, up
`Axis 1+` | Left Stick, down
`Full Axis 1-` | Left Stick, up
`Full Axis 1+` | Left Stick, down
`Axis 2-` | Left Trigger
`Axis 2+`  | Left Trigger
`Full Axis 2-` | Left Trigger
`Full Axis 2+` | Left Trigger
`Axis 3-` | Right Stick, Left
`Axis 3+` | Right Stick, Right
`Full Axis 3-` | Right Stick, Left
`Full Axis 3+` | Right Stick, Right
`Axis 4-` | Right Stick, Up
`Axis 4+` | Right Stick, Down
`Full Axis 4-` | Right Stick, Up
`Full Axis 4+` | Right Stick, Down
`Axis 5-` | Right Trigger
`Axis 5+` | Right Trigger
`Full Axis 5-` | Right Trigger
`Full Axis 5+` | Right Trigger

**Comment by Venomalia** [comment]
should work now
https://github.com/Venomalia/UniversalDynamicInput/archive/refs/heads/main.zip
