### ISSUE TITLE
Switch Pro Controller errors with SDL and DSU (BetterJoy)

### ISSUE THREAD

**Issue by alfredo-escobar** [Venomalia/UniversalDynamicInput#115]
### Dolphin version?

5.0-17269

### Operating System?

Windows 10

### Describe the bug.

- [x] In the JSONs, under the DSUClient/0/BetterJoy entry, the "Share" key is mapped to the "-" button texture. BetterJoy outputs a "Share" press when the Capture button is pressed, and "Touch" when the - button is pressed.
- [X]  In the JSONs, the SDL entry for the Pro Controller is listed as "SDL/0/Switch Pro Controller". Dolphin recognizes the Pro Controller as "SDL/0/Nintendo Switch Pro Controller".

**Comment by blindaman** [comment]
I just encountered this issue as well. The best solution I've come to is opening all the JSON files for all the games you wish to play in Notepad++ and you can replace all appearances of "SDL/0/Switch Pro Controller" with "SDL/0/Nintendo Switch Pro Controller" simultaneously. Make sure to save all the files after editing but that has worked for me so far.

**Comment by Venomalia** [comment]
maybe this is due to the revision of the controller, i will just write both in the pack json.

**Comment by Venomalia** [comment]
`SDL/0/Switch Pro Controller` should work now
https://github.com/Venomalia/UniversalDynamicInput/archive/refs/heads/main.zip

**Comment by Venomalia** [comment]
fix https://github.com/Venomalia/UniversalDynamicInput/commit/f86158ddad2eda3e0f200b9f955ce9adf1d70e63
