### ISSUE TITLE
Missing select button, DKCR, Xbox Series X Controller, Linux

### ISSUE THREAD

**Issue by shawnshyguy** [Venomalia/UniversalDynamicInput#134]
### Game Name?

DK Country Returns

### Game ID?

SF8E01

### Input device ID?

/evdev/0/Xbox Wireless Controller

### Dolphin version?

5.0-17269

### Operating System?

Arch Linux

### Describe the bug.

Select button prompt shows "?" when game prompts for whatever you have mapped to "Select". In this case, DKCR is prompting for "-", and UDI interprets that and shows a "?". When changing my button mapping so that "Start" is mapped to "-" instead, it shows the "Start" prompt fine. 

With Select as Minus:
![Screenshot_20221120_235254](https://user-images.githubusercontent.com/18062048/202984978-26114572-ff68-47c4-848b-9d96024a1850.png)
![Screenshot_20221120_235256](https://user-images.githubusercontent.com/18062048/202984990-64bbc57a-8c4c-4e5b-abab-f7291b6cc227.png)

With Start as Minus:
![Screenshot_20221120_235656](https://user-images.githubusercontent.com/18062048/202985011-b707bd12-0ede-4968-a337-2ce702fff662.png)
![Screenshot_20221120_235734](https://user-images.githubusercontent.com/18062048/202985014-9dd4d511-0fc7-484d-98fa-e9f73536c159.png)

### Expected behavior.

game shows correct correlating button prompt.

**Comment by Venomalia** [comment]
is it fixed now?

**Comment by Venomalia** [comment]
since i get no answer and the json looks good so far i close the issues
https://github.com/Venomalia/UniversalDynamicInput/blob/main/Donkey%20Kong%20Country%20Returns/UniversalDIT_Defaultstyle_Mirror.json#L674
