### ISSUE TITLE
Google Stadia Controller - Bluetooth Mode

### ISSUE THREAD

**Issue by JustMeIon** [Venomalia/UniversalDynamicInput#151]
### Input device?

Google Stadia Controller

### Input device ID?

DInput/0/Stadia Controller rev. A

### Operating System?

Windows 11

### What is the key assignment.

Stadia has added native Bluetooth Support. Here it is in Bluetooth Mode.

"`Button 0`" = A
"`Button 1`" = B
"`Button 2`" = X
"`Button 3`" = Y
"`Button 4`" = L1
"`Button 5`" = R1
"`Button 6`" = L3
"`Button 7`" = R3
"`Button 8`" = Options
"`Button 9`" = Menu
"`Button 10`" = Stadia / Home
"`Button 11`" = R2
"`Button 12`" = L2
"`Button 13`" = Google Assistant
"`Button 14`" = Screenshot
"`Hat 0 N`" = D-Pad Up
"`Hat 0 E`" = D-Pad Right
"`Hat 0 S`" = D-Pad South
"`Hat 0 W`" = D-Pad Left
"`Axis Z+`" = Right Stick Tilt Right
"`Axis Z-`" = Right Stick Tilt Left
"`Axis Zr-`" = Right Stick Tilt Up
"`Axis Zr+`" = Right Stick Tilt Down
"`Axis X-`" = Left Stick Tilt Left
"`Axis X+`" = Left Stick Tilt Right
"`Axis Y+`" = Left Stick Tilt Down
"`Axis Y-`" = Left Stick Tilt Up

![image](https://user-images.githubusercontent.com/99757408/213493955-fdbc80ac-d540-4a20-8a99-ed9bf1ac8c61.png)

![image](https://images.hothardware.com/contentimages/newsitem/49900/content/small_stadia_controller_buttons_diagram.jpg)

**Comment by Venomalia** [comment]
#73 the assignment and the id is the same.
So it should work already.

**Comment by JustMeIon** [comment]
After some testing, yeah. It's the same. My mistake.
