### ISSUE TITLE
Add ability to exchange texture for specific controller/device

### ISSUE THREAD

**Issue by Tom3s** [Venomalia/UniversalDynamicInput#155]
### For which game?

all

### Game ID?

-

### For which device?

Xinput/1/Gamepad

### what should we do?

Depending on the number of the controller (Xinput/0/Gamepad, Xinput/1/Gamepad, Xinput/2/Gamepad), use different textures.

For example Xinput/0/Gamepad would use the default XBOX textures, while Xinput/1/Gamepad would use textures for a DualShock controller. Would be handy if someone owns multiple types of controllers, and some of them are DS styled, yet still Xinput.

**Comment by Venomalia** [comment]
This is currently not possible from a purely technical point of view.
