### ISSUE TITLE
All button prompts upside down in Primehack for Prime 1 and 2GC

### ISSUE THREAD

**Issue by Zeldaman259** [Venomalia/UniversalDynamicInput#156]
### Game Name?

Metroid Prime 1 GC and 2 GC

### Game ID?

GM8E01 and G2ME01

### Input device ID?

Evdev/0/Microsoft Xbox 360 pad 0

### Dolphin version?

Latest version of Primehack, I dunno the numbers

### Operating System?

Steam OS

### Describe the bug.

They display upside down, all of them

### Expected behavior.

They’re supposed to display right side up

**Comment by Zeldaman259** [comment]
Upon further inspection, it happens in normal dolphin too, but only with the prime games

**Comment by Venomalia** [comment]
the bug seems to be present in 1.9, but it seems to be fixed already.
https://github.com/Venomalia/UniversalDynamicInput/archive/refs/heads/main.zip

**Comment by Zeldaman259** [comment]
> the bug seems to be present in 1.9, but it seems to be fixed already.
> https://github.com/Venomalia/UniversalDynamicInput/archive/refs/heads/main.zip

That didn’t seem to fix it, I switched to prime trilogy and it’s still there in trilogy

**Comment by cd216513** [comment]
I too am still seeing all button prompts upside down on Prime Trilogy through Prime Hack on Steam Deck, leveraging the latest in main

**Comment by Venomalia** [comment]
the jsons for the game and the controller look right,
all are on the mirrored versions, because the game should mirror them.
but for some reason there is an error here, could you check if your file looks like this?
https://github.com/Venomalia/UniversalDynamicInput/blob/main/Metroid%20Prime_Wii/UniversalDIT_Flat_Mirror.json#L1123

**Comment by Zeldaman259** [comment]
I copy pasted the stuff from that JSON into mine and everything works now

**Comment by Venomalia** [comment]
so it is fixed after all, probably you just did not overwrite the files when testing the main.

**Comment by Venomalia** [comment]
2.0 is now also available
