### ISSUE TITLE
Missing Support for WGInput/0/Xbox One Game Controller

### ISSUE THREAD

**Issue by tangomike99** [Venomalia/UniversalDynamicInput#160]
Thank you all for your time and effort on this tool. It really takes emulation quality to another level.

I see in the [documentation](https://github.com/Venomalia/UniversalDynamicInput/wiki/Supported-Input-Devices) that the WGInput/0/Xbox One Game Controller input device is supported. However, I had a couple of issues that I had to manually address to get that device working.

First of all, the "UniversalDIT_Flat.json" files provided in the 1.9 release are missing the mapping for this input device. I found that it is present in the repository file (example [here](https://github.com/Venomalia/UniversalDynamicInput/blob/main/ATV%20Quad%20Power%20Racing%202/UniversalDIT_Flat.json#L1250)), so I only had to copy that file's contents to the game directories that I wanted to use. I suppose this may be due to the release simply being outdated.

I also noticed that the "[UniversalDIT_Devices.json](https://github.com/Venomalia/UniversalDynamicInput/blob/main/New%20Super%20Mario%20Wii/UniversalDIT_Devices.json)" file for New Super Mario Wii did not have a mapping for WGInput/0/Xbox One Game Controller. That was a simple thing to correct to get this game working for me. I also noticed that this file is not present in the #Assets folder, so perhaps this game file is being overlooked (if my understanding of this tool is correct).

Are these issues or is this expected?

Thank you in advance for your time and support. Please let me know if there is any additional information or help that I can provide.

**Comment by Venomalia** [comment]
1. 1.9 is somewhat outdated.
but you can also download the main: https://github.com/Venomalia/UniversalDynamicInput/archive/refs/heads/main.zip

2. that the Devices.json is not up to date is to be expected.
These are not standardized and are updated irregularly.

**Comment by Venomalia** [comment]
2.0 is now available

**Comment by tangomike99** [comment]
Thank you very much, @Venomalia . I appreciate your support!
