### ISSUE TITLE
[Feature Request] Nefarious DS3 Driver

### ISSUE THREAD

**Issue by Daisouji** [Venomalia/UniversalDynamicInput#162]
### Input device?

Playstation 3

### Input device ID?

SDL/0/Nefarius Software Solutions e.U. DS3 Compatible HID Device

### Operating System?

Windows 10

### What is the key assignment.

```
"`Button 0`" = Cross
"`Button 1`" = Circle
"`Button 2`" = Square
"`Button 3" =  Triangle
"`Button 4`" = L1
"`Button 5`" = R1
"`Button 6`" = Select
"`Button 7" = Start
"`Button 8`" = L Stick
"`Button 9`" = R Stick
"`Button 10" = Guide
"`Hat 0 N`" = Up
"`Hat 0 E`" =  Left
"`Hat 0 S`" =  Down
"`Hat 0 W`" = Right
"`Axis Z+`" = L-Trigger
"`Axis Z-`" =  R - Trigger
"`Axis X-`" =  Left
"`Axis X+`" = Right
"`Axis Y+`" =  Down
"`Axis Y-`" = Up
"`Axis Xr-`" = (Right Stick) Left
"`Axis Xr+`" = (Right Stick) Right
"`Axis Yr+`" = (Right Stick) Down
"`Axis Yr-`" =  (Right Stick) Up

```

**Comment by Daisouji** [comment]
Just in case, I didn't spell it right.
<img width="296" alt="Capture" src="https://user-images.githubusercontent.com/82060898/219502422-eee92f76-28db-48bb-9ef1-44461a7753fb.PNG">

**Comment by Venomalia** [comment]
that is a name. 😆 
everything looks fine.

**Comment by Daisouji** [comment]
Yeah, it's the DS3 Driver name from https://github.com/ViGEm/DsHidMini
