### ISSUE TITLE
Xbox Series X controller not working on mac

### ISSUE THREAD

**Issue by schrammalama** [Venomalia/UniversalDynamicInput#176]
As the title suggests its not recognizing my series controller. I think the issue is that it shows up under 2 options in dolphin Input/0/Xbox Wireless Controller and SDL/0/Xbox Series X Controller. Neither of which are on the supported list. Please fix this.

**Comment by Venomalia** [comment]
I need the key mapping to add a controller, please use the [Device Request](https://github.com/Venomalia/UniversalDynamicInput/issues/new?assignees=&labels=Device+Request&projects=&template=device_request.yml).
