### ISSUE TITLE
Xbox Series X Controller bluetooth on MacOS

### ISSUE THREAD

**Issue by thibthib17** [Venomalia/UniversalDynamicInput#186]
### Input device?

Xbox Series X Controller

### Input device ID?

SDL/0/Xbox Series X Controller

### Operating System?

Macos 12.6.7 (Monterey)

### What is the key assignment.

"`Button 0`" = Button A (green)
"`Button 1`" = Button B (red)
"`Button 2`" = Button X (blue)
"`Button 3`" = Button Y (yellow)
"`Button 4`" =  Back
"`Button 5`" = Guide (X logo)
"`Button 6`" = Start
"`Button 7`" = Thumb L
"`Button 8`" = Thumb R
"`Button 9`" = Shoulder L
"`Button 10`" = Shoulder R
"`Button 11`" = D-pad UP
"`Button 12`" = D-pad Down
"`Button 13`" = D-pad Left
"`Button 14`" = D-pad Right
"`Button 15`" = Share
"`Axis 0+`" = Left Stick Right
"`Axis 0-`" = Left Stick Left
"`Axis 1+`" = Left Stick Down
"`Axis 1-`" = Left Stick UP
"`Axis 2+`" = Right Stick Right
"`Axis 2-`" = Right Stick Left
"`Axis 3+`" = Right Stick Down
"`Axis 3-`" = Right Stick UP
"`Full Axis 4+`" = Trigger L
"`Full Axis 5+`" = Trigger R

**Comment by Venomalia** [comment]
same as #183
