### ISSUE TITLE
Keyboard support for PrimeHack

### ISSUE THREAD

**Issue by Clozent** [Venomalia/UniversalDynamicInput#187]
### Game Name?

Metroid Prime Trilogy

### Game ID?

R3MP01

### Upload the Textures dumps for the game.

[0EXTRA - PrimeHack MKB Icons.zip](https://github.com/Venomalia/UniversalDynamicInput/files/12158482/0EXTRA.-.PrimeHack.MKB.Icons.zip)

The buttons should probably look like the ones in this zip folder, since it fits the game's aesthetic.
I found these textures here:
https://forums.dolphin-emu.org/Thread-metroid-prime-trilogy-hd-interface-textures-v-1-7-may-01-2021?pid=527477&highlight=primehack#pid527477

And I think they were made using the custom texture tool:
https://forums.dolphin-emu.org/Thread-custom-texture-tool-ps-v50-1

**Comment by Venomalia** [comment]
Since you are not the creator we can not use it for this projekt.
