### ISSUE TITLE
Is Android supported?

### ISSUE THREAD

**Issue by KUGA2** [Venomalia/UniversalDynamicInput#195]
### What is your question?

Is this plugin supported with the android version of dolphin?

(The load path is shown in Config->Path: /storage/emulated/0/Android/data/org.dolphinemu.dolphinemu/files/Load)

I cannot test this cause my controller (GameSir X2 Type C) is not supported

**Comment by Venomalia** [comment]
the pack currently does not support Android.

**Comment by KUGA2** [comment]
Ok, thats sad. Think about mentioning this in the Readme.

**Comment by Venomalia** [comment]
It can be found on the wiki
