### ISSUE TITLE
Sonic Colours Gamecube X and Y swapped

### ISSUE THREAD

**Issue by Voovoodoo** [Venomalia/UniversalDynamicInput#209]
### Game Name?

Sonic Colours

### Game ID?

SNCE8P

### Input device ID?

Xinput/0/Gamepad

### Dolphin version?

19903

### Operating System?

Windows 10

### Describe the bug.

The textures for ingame prompts are mapped wrong between X and Y (tex1_384x256_5f9afb8ee67caca1_3.png, UniversalDIT_Flat.json), ingame this results in prompts for the X button (GC) overlaying textures mapped to Y instead:

        "GCPad1": {
          "Buttons/X": [
            [
              128.0, (should be 256)
              384.0,
              256.0, (should be 384)
              512.0
            ]
          ],
          "Buttons/Y": [
            [
              256.0, (should be 128)
              384.0,
              384.0, (should be 256)
              512.0

### Expected behavior.

Gamecube prompts ingame for X and Y should be mapped properly.

**Comment by Venomalia** [comment]
will be fixed.
![grafik](https://github.com/Venomalia/UniversalDynamicInput/assets/87765258/26f97250-6889-41c4-9f72-593d1d356b2f)
