### ISSUE TITLE
8bitDo Pro 2 Wired Controller

### ISSUE THREAD

**Issue by JJWrek** [Venomalia/UniversalDynamicInput#215]
### Input device?

8bitDo Pro 2 Wired Controller

### Input device ID?

SDL/0/(8bitDo Pro 2 Wired Controller)

### Operating System?

Windows 11

### What is the key assignment.

"`Button 0`" = B
"`Button 1`" = A
"`Button 2`" = Y
"`Button 3`" = X
"`Button 4`" = 
"`Button 5`" = Z
"`Button 6`" =
"`Button 7`" = START
"`Button 8`" =
"`Button 9`" =
"`Button 10`" =
"`Button 11`" =
"`Button 12`" =
"`Button 13`" =
"`Button 14`" =
"`Button 15`" =
"`Hat 0 N`" = Up
"`Hat 0 E`" = Right
"`Hat 0 S`" = Down
"`Hat 0 W`" = Left
"`Axis 0+`" = LS Right
"`Axis 0-`" = LS Left
"`Axis 1+`" = LS Down
"`Axis 1-`" = LS Up
"`Axis 2+`" = CS Right
"`Axis 2-`" = CS Left
"`Axis 3+`" = CS Down
"`Axis 3-`" = CS Up
"`Full Axis 4+`" = L
"`Full Axis 5+`" = R

**Comment by Venomalia** [comment]
What about RB, LB, RT, LT and the extra buttons?
