### ISSUE TITLE
Batocera support 

### ISSUE THREAD

**Issue by Ammar1313** [Venomalia/UniversalDynamicInput#216]
### Input device?

DuelShock 4

### Input device ID?

Wireless controller 

### Operating System?

Batocera

### What is the key assignment.

"`Button 1`" = 
"`Button 2`" =
"`Button 3`" =
"`Button 4`" =
"`Button 5`" =
"`Button 6`" =
"`Button 7`" =
"`Button 8`" =
"`Button 9`" =
"`Button 10`" =
"`Button 11`" =
"`Button 12`" =
"`Button 13`" =
"`Button 14`" =
"`Button 15`" =
"`Hat 0 N`" =
"`Hat 0 E`" =
"`Hat 0 S`" =
"`Hat 0 W`" =
"`Axis Z+`" =
"`Axis Z-`" =
"`Axis X-`" =
"`Axis X+`" =
"`Axis Y+`" =
"`Axis Y-`" =
"`Axis Xr-`" =
"`Axis Xr+`" =
"`Axis Yr+`" =
"`Axis Yr-`" =

**Comment by Venomalia** [comment]
Linux operating systems are supported, as long as the device ID in dolphin is the same.
As no further details were given, i assume that this is a set-up error.

if you can't get it to work, please check this page to see if it helps
https://github.com/Venomalia/UniversalDynamicInput/wiki/Problem-solving
