### ISSUE TITLE
Batocera support

### ISSUE THREAD

**Issue by indiepedia** [Venomalia/UniversalDynamicInput#218]
### What is your question?

Hi,
I'm trying to run your universal dynamic input on my Batocera (v38) but unfortunately all I see is ? buttons.
I use the PS4's DualShock.
The analog sticks were recognized. I have tried everything described in the FAQ under ? Buttons, but couldn't find a solution.
Is there anything special to configure Delphin on Batocera?

**Comment by Venomalia** [comment]
No all desktop versions should be supported the feature is from dolphin itself not this pack.
so the solution should be here https://github.com/Venomalia/UniversalDynamicInput/wiki/Problem-solving#i-see--buttons

since you have apparently already tried this?
Can you send your `GCPadNew.ini` if it is a gc game or `WiimoteNew.ini` if it is a wii game, you can find this in the user directory in the `Config` folder.

**Comment by indiepedia** [comment]
[GCPadNew.zip](https://github.com/Venomalia/UniversalDynamicInput/files/13885688/GCPadNew.zip)
Thanks for your help
It's dolphin 5.0-19864 on batocera v38

**Comment by indiepedia** [comment]
i found a solution:
i rename the buttons of my controller in every single UniversalDIT_Defaultstyle of the games on my Batocera System, because the have a different name in GCPadNew.ini.

**GCPadNew.ini**
[GCPad1]
Device = evdev/0/Wireless Controller
Buttons/A = `Button 1`
Rumble/Motor = Weak
Buttons/B = `Button 0`
D-Pad/Down = `Axis 7+`
Buttons/Hotkey = `Button 10`
Main Stick/Left = `Axis 0-`
Main Stick/Right = `Axis 0+`
Main Stick/Up = `Axis 1-`
Main Stick/Down = `Axis 1+`
C-Stick/Left = `Axis 3-`
C-Stick/Right = `Axis 3+`
C-Stick/Up = `Axis 4-`
C-Stick/Down = `Axis 4+`
Triggers/L = `Axis 2+`
D-Pad/Left = `Axis 6-`
Buttons/Z = `Button 5`
Triggers/R = `Axis 5+`
D-Pad/Right = `Axis 6+`
Buttons/Start = `Button 9`
D-Pad/Up = `Axis 7-`
Buttons/X = `Button 2`
Buttons/Y = `Button 3`
Main Stick/Modifier/Range = 50.0
C-Stick/Modifier/Range = 50.0
[GCPad2]
Main Stick/Modifier/Range = 50.0
C-Stick/Modifier/Range = 50.0
[GCPad3]
Main Stick/Modifier/Range = 50.0
C-Stick/Modifier/Range = 50.0
[GCPad4]
Main Stick/Modifier/Range = 50.0
C-Stick/Modifier/Range = 50.0

**UniversalDIT_DefaultStyle**
    "evdev/0/Wireless Controller": {
      "evdev/0/Wireless Controller": "../#DefaultDevices/DualShock4/Device/Icon.png",
      "`Button 0`": "../#DefaultDevices/DualShock4/Flat/Cross.png",
      "`Button 1`": "../#DefaultDevices/DualShock4/Flat/Circle.png",
      "`Button 3`": "../#DefaultDevices/DualShock4/Flat/Square.png",
      "`Button 2`": "../#DefaultDevices/DualShock4/Flat/Triangle.png",
      "`Button 4`": "../#DefaultDevices/DualShock4/Flat/L1.png",
      "`Button 5`": "../#DefaultDevices/DualShock4/Flat/R1.png",
      "`Axis 2+`": "../#DefaultDevices/DualShock4/Flat/L2.png",
      "`Axis 5+`": "../#DefaultDevices/DualShock4/Flat/R2.png",
      "`Button 9`": "../#DefaultDevices/DualShock4/Flat/Options.png",
      "`Button 8`": "../#DefaultDevices/DualShock4/Flat/Share.png",
      "`Button 10`": "../#DefaultDevices/DualShock4/Flat/PS.png",
      "LEFT": "../#DefaultDevices/DualShock4/Flat/Touchpad.png",
      "`Axis 7-`": "../#DefaultDevices/DualShock4/Flat/Pad N.png",
      "`Axis 7+`": "../#DefaultDevices/DualShock4/Flat/Pad S.png",
      "`Axis 6+`": "../#DefaultDevices/DualShock4/Flat/Pad E.png",
      "`Axis 6-`": "../#DefaultDevices/DualShock4/Flat/Pad W.png",
      "`Axis 1+`": "../#DefaultDevices/DualShock4/Flat/Left Y-.png",
      "`Axis 1-`": "../#DefaultDevices/DualShock4/Flat/Left Y+.png",
      "`Axis 0+`": "../#DefaultDevices/DualShock4/Flat/Left X+.png",
      "`Axis 0-`": "../#DefaultDevices/DualShock4/Flat/Left X-.png",
      "`Button 11`": "../#DefaultDevices/DualShock4/Flat/L3.png",
      "`Axis 4+`": "../#DefaultDevices/DualShock4/Flat/Right Y-.png",
      "`Axis 4-`": "../#DefaultDevices/DualShock4/Flat/Right Y+.png",
      "`Axis 3+`": "../#DefaultDevices/DualShock4/Flat/Right X+.png",
      "`Axis 3-`": "../#DefaultDevices/DualShock4/Flat/Right X-.png",
      "`Button 12`": "../#DefaultDevices/DualShock4/Flat/R3.png"
    },

**Comment by mcdbos49** [comment]
I'm having the same problem with my Xbox Series X controller. Do you know where GCPad.ini is located in Batocera so I can fine mine and fix this as well?
