### ISSUE TITLE
Xenoblade Chronicles textures not loading. 

### ISSUE THREAD

**Issue by rishaba1998** [Venomalia/UniversalDynamicInput#224]
### Game Name?

Xenoblade Chronicles

### Game ID?

SX4

### Input device ID?

XInput/0/Gamepad

### Dolphin version?

5.0-21088

### Operating System?

Windows 10

### Describe the bug.

The controller icon textures for xenoblade chronicles aren't even loading at all. I am using an Xbox controller. I had to download a separate pack just to see Xbox icons. 

### Expected behavior.

I want to see Xbox one icons when I play the game.

**Comment by Venomalia** [comment]
it is likely that you have set something up incorrectly https://github.com/Venomalia/UniversalDynamicInput/wiki/Problem-solving

**Comment by Venomalia** [comment]
closed, no reply from issues creator.
