### ISSUE TITLE
Support for Kirby Air Ride Hack Pack

### ISSUE THREAD

**Issue by Afrocntrik** [Venomalia/UniversalDynamicInput#240]
### Game Name?

Kirby Air Ride

### Game ID?

GKY/KHPE01

### Input device ID?

Xinput/0/Gamepad

### Dolphin version?

5.0-21200

### Operating System?

Windows 11

### Describe the bug.

Firstly I just want to preface I added KHPE01.txt [Kirby Air Ride Hack Pack] as an additional file in GameID and it worked great.
Regardless on line 2166 "tex1_168x32_74cd9021a1965cf0_14.png" in the "UniversalDIT_Flat.json" should be renamed to "tex1_168x32_40eebf538b65fc35_371c6161b7b43c36_8.png" along with the corresponding file as it does not apply the settings texture at all Custom Textures Notification supports that with 7 being loaded before the fix.

Before:
![image](https://github.com/Venomalia/UniversalDynamicInput/assets/11052983/81bc7893-42f5-4137-bc43-262e9b9311bb)

I also tried to fix the transparency issue for the icons being applied it seems it may be a Dolphin issue on how it applies a file with transparency to a dynamic texture.

### Expected behavior.

This is after the fix 8 Custom Textures were Loaded:
![image](https://github.com/Venomalia/UniversalDynamicInput/assets/11052983/7c2b4e2e-13bf-4f6f-bfad-f959792eb242)

**Comment by Venomalia** [comment]
This is not a bug, simply other textures are used that are not present in the pack yet.
I could fix this when I have time or you could create a pull request, to support Kirby Air Ride Hack Pack.
