### ISSUE TITLE
Digimon World 4 Game Request

### ISSUE THREAD

**Issue by dude98** [Venomalia/UniversalDynamicInput#37]
### Game Name?

Digimon World 4

### Game ID?

GDJEB2

### Upload the Textures dumps for the game.

![tex1_512x512_38dbb14aaf216201_3e25af75842572c5_9](https://user-images.githubusercontent.com/13279963/142126758-c17aed5a-e4b6-422e-a66b-6e11c8b1f130.png)
This seems to be the whole font/controller icon png that the game uses, i tested by replacing the A button with a blue box and it appeared in multiple places, including the save menu, character creation, and the start menu. it also holds the text for dialog, so i assume it's the same there too.

**Comment by Venomalia** [comment]
I need the texturn name! because the texture is not in a zip and the original name is lost.

**Comment by dude98** [comment]
[Digimon World 4 Universal Controller texture.zip](https://github.com/Venomalia/UniversalDynamicInput/files/7557486/Digimon.World.4.Universal.Controller.texture.zip)
Here, that should have it named.

**Comment by Venomalia** [comment]
[Digimon World 4.zip](https://github.com/Venomalia/UniversalDynamicInput/files/7558057/Digimon.World.4.zip)
here is the finished package if you want to test it already.

**Comment by dude98** [comment]
it works in the menus, so i'm guessing it works in dialog boxes too.
