### ISSUE TITLE
no textures are being made

### ISSUE THREAD

**Issue by dude98** [Venomalia/UniversalDynamicInput#40]
whenever i launch a game, i get a folder that has the gameid, but no files that actually show the buttons, as well as a 0.0mbs loaded in 0 seconds message

**Comment by dude98** [comment]
i tried running the dolphindynamicinputtexturecreator.exe file, and it said i don't have net core installed, so i'm installing it now to see if it fixes it.

**Comment by dude98** [comment]
apparently the latest version of dolphin (5.0-15568) cannot make the textures.

**Comment by Venomalia** [comment]
> i tried running the dolphindynamicinputtexturecreator.exe file, and it said i don't have net core installed, so i'm installing it now to see if it fixes it.

This package does not use generated folders with game IDs,  `#Generated_<Game_name>`

> i tried running the dolphindynamicinputtexturecreator.exe file, and it said i don't have net core installed, so i'm installing it now to see if it fixes it.

the dolphin dynamic input texture creator i use to create packages.

> apparently the latest version of dolphin (5.0-15568) cannot make the textures.
i ran an older version and they generated fine, but this version can't.

I have tried it with the 5.0-15571 without problems

**Comment by Venomalia** [comment]
if you try to make your own package look [here](https://github.com/Venomalia/UniversalDynamicInput/wiki/Create-a-Package)

**Comment by dude98** [comment]
an update must have fixed it, because now it's generating.
