### ISSUE TITLE
Game Request

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#61]
### Game Name?

Skylanders: Spyro's Adventure

### Game ID?

SSPE52

### Upload the Textures dumps for the game.

[Textures.zip](https://github.com/Venomalia/UniversalDynamicInput/files/7965014/Textures.zip)

**Comment by Venomalia** [comment]
here is the finished package if you want to test it.
[Skylanders Spyros Adventure.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8007752/Skylanders.Spyros.Adventure.zip)

**Comment by Fraisk** [comment]
After some testing, i have found a few issues.
![issues](https://user-images.githubusercontent.com/32005929/152649795-b9a51ab9-6479-426d-9135-e2a7123990bd.png)
 Some Buttons do work, others, don't for some reason like the menu buttons, they don't work, but the buttons on the bow to play menu, do? Also The A button Is used even though i'm using a PS4 preset

![image](https://user-images.githubusercontent.com/32005929/152649849-5fcd1eb5-8a2b-419b-88bb-337f5ac56788.png)
Also the button where you attempt to interact with characters, is a texture i missed, that's an oops on my part, i can't for the life of me dump the texture with dolphin, but i THINK i know the name of the texture.

tex1_64x64_m_de90ae2c9f448ba9_14

**Comment by Fraisk** [comment]
lol jk found the missing texture, plus some mip maps too
[C.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8008390/C.zip)
!

**Comment by Venomalia** [comment]
The A & C button are corrected, maybe an overlay texture is missing for the C button.
For the B button I could not find any error, maybe some textures are still missing.
[Skylanders Spyros Adventure.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8008923/Skylanders.Spyros.Adventure.zip)

**Comment by Fraisk** [comment]
Ok, i think i found the missing textures? Maybe
[i need practice lol.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8008979/i.need.practice.lol.zip)
?

**Comment by Venomalia** [comment]
then I guess it works now.
[Skylanders Spyros Adventure.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8009005/Skylanders.Spyros.Adventure.zip)

**Comment by Fraisk** [comment]
Sweet, everything shows up, there's just a few issues that need fixin
![save](https://user-images.githubusercontent.com/32005929/152661204-a255f4f1-d1c0-4ecf-968d-8e4f3066e58e.png)
![bruh](https://user-images.githubusercontent.com/32005929/152661206-cfde5651-409e-4182-b496-d0662dc47f78.png)
g

**Comment by Venomalia** [comment]
the d-pad has to stay like this for now.
otherwise I hope that everything works now
[Skylanders Spyros Adventure.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8010006/Skylanders.Spyros.Adventure.zip)

**Comment by Fraisk** [comment]
Eh, there are still some clipping issues, but yeah, everything works now!
