### ISSUE TITLE
Game Rquest 2

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#62]
### Game Name?

Tom And Jerry in War Of The Whiskers

### Game ID?

GTJE5L

### Upload the Textures dumps for the game.

[War Of The Whiskers.zip](https://github.com/Venomalia/UniversalDynamicInput/files/7999890/War.Of.The.Whiskers.zip)

**Comment by Venomalia** [comment]
[Tom And Jerry in War Of The Whiskers.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8007805/Tom.And.Jerry.in.War.Of.The.Whiskers.zip)

**Comment by Fraisk** [comment]
After some testing, i can confrim that this 100% works!
