### ISSUE TITLE
Game Request 3

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#64]
### Game Name?

Rabbids Go Home

### Game ID?

RGWE41

### Upload the Textures dumps for the game.

[Rabbids Go Home.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8006898/Rabbids.Go.Home.zip)

**Comment by Venomalia** [comment]
[Rabbids Go Home.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8007838/Rabbids.Go.Home.zip)

**Comment by Fraisk** [comment]
There are a few issues i found while testing.

![image](https://user-images.githubusercontent.com/32005929/152651970-985efbcd-fefa-48cb-9cd9-f9660d970fc3.png)

The the A button (X in this case) clips at the top.

![image](https://user-images.githubusercontent.com/32005929/152652038-f1cd7052-06f3-4022-86b0-dc30bc7a47d1.png)

And again, I missed yet another texture, don't worry though, I got the textures for that one, and some mipmaps.

[A.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8008469/A.zip)

**Comment by Venomalia** [comment]
[Rabbids Go Home.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8008943/Rabbids.Go.Home.zip)

**Comment by Fraisk** [comment]
After some testing, I can say it works! I mean there was this... but im just nitpicking at that point.
![image](https://user-images.githubusercontent.com/32005929/152660019-ffd46509-bcfd-4933-9733-b9ef7b8df71a.png)

**Comment by Venomalia** [comment]
I have improved the fine tuning a bit, but I can't do much more at the moment.

**Comment by Fraisk** [comment]
Don't worry, it's fine, really minor stuff, everything else works great!
