### ISSUE TITLE
Game Request 4

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#68]
### Game Name?

Teenage Mutant Ninja Turtles: Smash-Up

### Game ID?

R2TE41

### Upload the Textures dumps for the game.

[lol.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8010956/lol.zip)

**Comment by Fraisk** [comment]
Wait actually don't use that use this instead: 

[oops.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8010979/oops.zip)

**Comment by Venomalia** [comment]
I have not included the texture of the Wii Remote with Nunchuk for now.
[Teenage Mutant Ninja Turtles Smash-Up.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8014509/Teenage.Mutant.Ninja.Turtles.Smash-Up.zip)

**Comment by Fraisk** [comment]
Bug Report Time

![image](https://user-images.githubusercontent.com/32005929/152846596-cdeaa2e5-c282-4c73-b774-72850d07db6a.png)


The a and b button for the classic controler don't work, and the minus button only shows up if you map it to the wiimote and not the claasic controller itself



![image](https://user-images.githubusercontent.com/32005929/152846076-59c5d1ee-847a-46e7-9c42-ee505798757b.png)

![image](https://user-images.githubusercontent.com/32005929/152846239-d79347a7-06f1-4989-b4ff-93525d2c797b.png)


The Z button is different between the gc controller and the nunchuck, but the game uses the nunchuck z button anyway for the gc controller reset button? weird

**Comment by Venomalia** [comment]
should be better now, the minus button and also the +- and home button should always be assigned to the wii remote as well.
this is the case with all games.
[Teenage Mutant Ninja Turtles Smash-Up.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8018260/Teenage.Mutant.Ninja.Turtles.Smash-Up.zip)

**Comment by Fraisk** [comment]
Ok, more bugging time!

Not only does the gc controlller use the Nunchuck's Z button, but it ALSO uses the Wiimote's A button As Well!

![image](https://user-images.githubusercontent.com/32005929/152866137-00085872-7309-453c-82a2-f44e00374d9e.png)

Oh yeah, there's also a different button at the results screen

![image](https://user-images.githubusercontent.com/32005929/152866213-d57319a8-ba56-4060-bbb5-9e0854d6ad6b.png)

Here's the stuff for that 

[stuff.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8018462/stuff.zip)

**Comment by Venomalia** [comment]
the question is where is the "A" letter.

**Comment by Fraisk** [comment]
That's the issue, i can't find it, if i had to guess, it's probably used with the regular font used for text in game. try to change it and i'll see if it's that noticable or not

**Comment by Venomalia** [comment]
I assume that it is the font unfortunately I can not change it then.

**Comment by Fraisk** [comment]
Don't worry, it's fine, just a minor issue. Don't sweat it.
