### ISSUE TITLE
Game Request: Looney Tunes Acme Arsenal

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#70]
### Game Name?

Looney Tunes: Acme Arsenal

### Game ID?

RLYEWR

### Upload the Textures dumps for the game.

[arsenal.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8054823/arsenal.zip)

I Dont' Know How Well Dynamic Input Textures fares with Motion Control Textures, bu hey, guess it'll be a first time experience!

**Comment by Fraisk** [comment]
![tex1_64x64_1b4b60c83a9514a3_5](https://user-images.githubusercontent.com/32005929/153735675-7fc6bc37-a4b8-4615-9065-5b55c0bcb856.png)

My bad, missed a texture

**Comment by Fraisk** [comment]
My bad, missed a texture
[lol.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8056427/lol.zip)

**Comment by Venomalia** [comment]
> I Dont' Know How Well Dynamic Input Textures fares with Motion Control Textures, bu hey, guess it'll be a first time experience!

currently rather bad, however the new version of Dynamic Input Textures will come soon.

however, it still looks manageable.

**Comment by Fraisk** [comment]
Yeah i Can imagine, the wiimote shaking texture should be easy enough, just set it to the X part of the shake control, but as for spinning the nunchuck? I'm totally lost on how to implement THAT.

**Comment by Venomalia** [comment]
[Looney Tunes Acme Arsenal.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8069551/Looney.Tunes.Acme.Arsenal.zip)

**Comment by Venomalia** [comment]
![grafik](https://user-images.githubusercontent.com/87765258/154129080-ca1d9161-cddb-4e0c-a624-bb770df461f9.png)
I will not add this graphic for right now.

![grafik](https://user-images.githubusercontent.com/87765258/154129383-9d935c36-7900-439f-9399-089fd50190e0.png)
This is associated with nunschuk shake X

![grafik](https://user-images.githubusercontent.com/87765258/154129586-258ac894-36a2-44c3-99c0-487e02bdb2f4.png)
the other textures use some kind of mask, most of the time there is an associated texture, if not i can't do anything about it.

**Comment by Fraisk** [comment]
Alright then if that's the case, that's all folks! (Get it, b-because this is a looney Tunes Game? eh whatever)

**Comment by Venomalia** [comment]
couldn't you find any mask textures?
then I assume the game uses models for the buttons.

**Comment by Fraisk** [comment]
No, sadly, that's just how they show up in game, just a white texture, what you see with the wii and nunchuck texture is what you get, thankfully they don't show up that much in game, only the tutorial
