### ISSUE TITLE
Playstation 5 Controller Request

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#71]
### Input device?

Dualsense (Playstation 5 Controller)

### Input device ID?

DInput/0/Wireless Controller

### Operating System?

Windows 10

### What is the key assignment.

![dualsense-thumbnail-ps5-01-en-17jul20](https://user-images.githubusercontent.com/32005929/153794407-899416cb-bf7a-42e8-a62e-acf6288cecad.jpg)

**Comment by Fraisk** [comment]
Sorry if i made this too cluttered, I could try this again if you're confused.

**Comment by Venomalia** [comment]
It seems like the design and name is 1 to 1 with the ds4, i guess the controller is already supported.
would you test it?

**Comment by Fraisk** [comment]
Yup! everything is working!

**Comment by Fraisk** [comment]
Also For DS4Windows: Button 13 IS Touch Button, And Button 12 Is PS

**Comment by Fraisk** [comment]
Oh Yeah, Controller Name For Dualsense IS DSUClient/0/DS4Windows

**Comment by Venomalia** [comment]
have updated the entries in the wiki.
