### ISSUE TITLE
Stadia Controller Support

### ISSUE THREAD

**Issue by JustMeIon** [Venomalia/UniversalDynamicInput#73]
### Input device?

Stadia Controller

### Input device ID?

DInput/0/Stadia Controller rev. A

### Operating System?

Windows 11

### What is the key assignment.

I'm quite a big fan of Stadia and the controller itself. It'd be pretty nice to see it as an option for within this project. Here's a general look and layout of the entire controller:

![Google-Stadia-Controller](https://user-images.githubusercontent.com/99757408/154132388-4cc75aee-52eb-4291-942d-8738118a90f9.png)

This is the what the buttons correspond to within Windows and Dolphin:

"`Button 0`" = A
"`Button 1`" = B 
"`Button 2`" = X
"`Button 3`" = Y
"`Button 4`" = L1
"`Button 5`" = R1
"`Button 6`" = L3
"`Button 7`" = R3 
"`Button 8`" = Options
"`Button 9`" = Menu
"`Button 10`" = Stadia Button (Guide Button)
"`Button 11`" = R2
"`Button 12`" = L2
"`Button 13`" = Google Assistant Button
"`Button 14`" = Screenshot Button
"`Button 15`" = N/A
"`Hat 0 N`" = D-Pad Up
"`Hat 0 E`" = D-Pad Right
"`Hat 0 S`" = D-Pad Down
"`Hat 0 W`" = D-Pad Left
"`Axis Zr-`" = Right Stick Up
"`Axis Zr+`" = Right Stick Down
"`Axis Z+`" = Right Stick Right
"`Axis Z-`" = Right Stick Left
"`Axis X-`" = Left Stick Left
"`Axis X+`" = Left Stick Right
"`Axis Y+`" = Left Stick Down
"`Axis Y-`" = Left Stick Up

![General Idea](https://user-images.githubusercontent.com/99757408/154131488-ea227a17-db02-4512-a483-cf36042af09c.png)

A few note worthy issues:
-Windows Recognizes L2 and R2 as digital buttons despite being fully analog.
-There is no vibration detected in Dolphin
(On https://gamepad-tester.com/ it recognizes the triggers as analog and even offers vibration. Genuinely not sure why or how.)

Here are some super basic glyphs:
[Google Stadia.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8073962/Google.Stadia.zip)

If you'd like some additional testing, I'm more than willing to do so. Thanks!

**Comment by Venomalia** [comment]
that looks very understandable. 👍 
I do not know yet how I have time so I expect a few weeks.

**Comment by Venomalia** [comment]
> -Windows Recognizes L2 and R2 as digital buttons despite being fully analog.
> -There is no vibration detected in Dolphin

these errors will come from the drivers used in windows.
