### ISSUE TITLE
Game Request: Kirby's Epic Yarn

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#76]
### Game Name?

Kirby's Epic Yarn

### Game ID?

RK5E01

### Upload the Textures dumps for the game.

[yarn.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8145254/yarn.zip)

**Comment by Fraisk** [comment]
after playing some more of the game, i found more textures, so use this instead:
[updated yarn.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8145319/updated.yarn.zip)

**Comment by Venomalia** [comment]
buttons are ready, wii mode textures are not.
[Kirby's Epic Yarn.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8358024/Kirby.s.Epic.Yarn.zip)

**Comment by Fraisk** [comment]
After some testing, i've found a few bugs
![Screenshot 2022-03-27 152
![Screenshot 2022-03-27 154031](https://user-images.githubusercontent.com/32005929/160302197-6b31993f-36ba-4766-a200-88419eddde2f.png)
926](https://user-images.githubusercontent.com/32005929/160302132-7911996a-2744-40a8-b079-9479d82228d0.png)
![Screenshot 2022-03-27 152943](https://user-images.githubusercontent.com/32005929/160302140-5b73111e-a983-44f1-8c08-54c6a85785a4.png)
![Screenshot 2022-03-27 154023](https://user-images.githubusercontent.com/32005929/160302198-a781bbb1-eca0-479b-b25c-881a9d243cea.png)
Also, I've missed a few textures, They''l be here:
[textures.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8358545/textures.zip)

**Comment by Venomalia** [comment]
the game shares the texture mask which is why i can't prevent the green background. 

[Kirby's Epic Yarn.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8416333/Kirby.s.Epic.Yarn.zip)
