### ISSUE TITLE
Game Request: Metal Arms: Glitch In The System

### ISSUE THREAD

**Issue by Fraisk** [Venomalia/UniversalDynamicInput#77]
### Game Name?

Metal Arms: Glitch In The System

### Game ID?

GM5E7D

### Upload the Textures dumps for the game.

[metal arms.zip](https://github.com/Venomalia/UniversalDynamicInput/files/8147497/metal.arms.zip)

DISCLAIMER: Most of the textures from this zip are from the Metal Arms Mapping project, that's why most of the textures are xbox buttons.

**Comment by Venomalia** [comment]
due to the external resource I can not accept this, still many thanks for the work.
