### ISSUE TITLE
8BitDo Pro 2

### ISSUE THREAD

**Issue by Bownz** [Venomalia/UniversalDynamicInput#80]
### Input device?

8BitDo Pro 2

### Input device ID?

evdev/0/8BitDo Pro 2

### Operating System?

Batocera (Linux)

### What is the key assignment.

"SOUTH" = B Button
"EAST" = A Button
"C" = Y Button
"NORTH" = X Button
"WEST" = L1 Button
"TL" = -select button
"TR" = +start button
"`TL2`" =  Left Thumb Press (L3)
"`TR2`" = Right Thumb Press (R3)
"`Axis 0+`" =  Left Stick East
"`Axis 0-`" = Left Stick West
"`Axis 1+`" = Left Stick South
"`Axis 1-`" = Left Stick  North
"`Axis 3+`" = Right Stick East
"`Axis 3-` = Right Stick West
"`Axis 4+`" = Right Stick South
"`Axis 4-`" = Right Stick North
"`Axis 6+`" = Pad Right
"`Axis 6-`" = Pad Left
"`Axis 7-`" = Pad Up
"`Axis 7+`" = Pad Down
"`Full Axis 2+`" = Left Analog Trigger
"`Full Axis 5+`" = Right Analog Trigger

**Comment by Venomalia** [comment]
where is R1, R2, L2?

**Comment by JopStro** [comment]
R1 is "Z", and R2 and L2 are refered to as Right and Left Analog Triggers in the op

**Comment by Venomalia** [comment]
should work now
https://github.com/Venomalia/UniversalDynamicInput/archive/refs/heads/main.zip
