### ISSUE TITLE
PS2 Controller with Adapter for PC - Dolphin Gamecube Controller setting

### ISSUE THREAD

**Issue by Great-Asu800** [Venomalia/UniversalDynamicInput#92]
### Input device?

Twin USB Gamepad (PS2 Controller with adapter)

### Input device ID?

DInput/0/Twin USB Joystick

### Operating System?

Windows 10

### What is the key assignment.

"`Button 3`" = Buttons/A 
"`Button 2`" = Buttons/B 
"`Button 1`" = Buttons/X
"`Button 0`" = Buttons/Y
"`Button 4`" = Buttons/Z 
"`Button 9`" = Buttons/Start 
"`Axis Y-`" = Main Stick/Up
"`Axis Y+`" = Main Stick/Down 
"`Axis X-`" = Main Stick/Left 
"`Axis X+`" = Main Stick/Right
"`Axis Z-`" = C-Stick/Up 
"`Axis Z+`" = C-Stick/Down 
"`Axis Zr-`" = C-Stick/Left
"`Axis Zr+`" = C-Stick/Right
"`Button 5`" = Triggers/L 
"`Button 7`" = Triggers/R 
"`Button 5`" = Triggers/L-Analog
"`Button 7`" = Triggers/R-Analog 
"`Hat 0 N`" = D-Pad/Up 
"`Hat 0 S`" = D-Pad/Down 
"`Hat 0 W`" = D-Pad/Left 
"`Hat 0 E`" = D-Pad/Right

**Comment by Venomalia** [comment]
do you mean like this? please fill in missing buttons.
"Button 3" = X
"Button 2" = O
"Button 1" = ∆
"Button 0" = □
"Button 4" = R1
"?" = L1
"?" =selects
"Button 9" = Start
"Button 5" = L2
"Button 7" = R2

**Comment by Great-Asu800** [comment]
"Button 3" = Buttons/A -> □
"Button 2" = Buttons/B -> X
"Button 1" = Buttons/X -> O
"Button 0" = Buttons/Y -> ∆
"Button 4" = Buttons/Z -> L2
"Button 9" = Buttons/Start -> Start

"Button 5" = Triggers/L ->  R2
"Button 7" = Triggers/R -> R1

"Button 5" = Triggers/L-Analog ->  R2
"Button 7" = Triggers/R-Analog -> R1
"`Button 6`" -> L1
"`Button 8`" -> Select
"`Button 10` -> L3
"`Button 11` -> R3
