### ISSUE TITLE
Nintendo Switch Pro Controller (connected by bluetooth) - Dolphin Gamecube Controller Setting

### ISSUE THREAD

**Issue by Great-Asu800** [Venomalia/UniversalDynamicInput#93]
### Input device?

Pro Controller

### Input device ID?

DInput/0/Pro Controller

### Operating System?

Windows 10

### What is the key assignment.

"`Button 2`" = Buttons/A 
"`Button 0`" = Buttons/B
"`Button 1`" = Buttons/X 
"`Button 3` = Buttons/Y
"`Button 6`" = Buttons/Z
"`Button 9`" = Buttons/Start
"`Axis Y-`" = Main Stick/Up 
"`Axis Y+`" = Main Stick/Down 
"`Axis X-`" = Main Stick/Left 
"`Axis X+`" = Main Stick/Right
"`Axis Yr-`" = C-Stick/Up
"`Axis Yr+`" = C-Stick/Down
"`Axis Xr-`" = C-Stick/Left
"`Axis Xr+`" = C-Stick/Right 
"`Button 7`" = Triggers/L
"`Button 5`" = Triggers/R
"`Button 7`" = Triggers/L-Analog
"`Button 5`" = Triggers/R-Analog
"`Hat 0 N`" = D-Pad/Up 
"`Hat 0 S`" = D-Pad/Down 
"`Hat 0 W`" = D-Pad/Left
"`Hat 0 E`" = D-Pad/Right

**Comment by Venomalia** [comment]
"Button 6" = L?
"?" = R
"Button 7" = LZ?
"Button 5" = RZ?

"Button 9" = Home?
"?" =  Screenshot Button
"?" = +
"?" = -

**Comment by Great-Asu800** [comment]
"Button 6" = Buttons/Z -> ZL
"Button 7" = Triggers/L -> ZR
"Button 5" = Triggers/R -> R
"Button 7" = Triggers/L-Analog -> ZR 
"Button 5" = Triggers/R-Analog -> R
"`Button 4`" -> L
"Button 12" = Home
"Button 13" = Screenshot Button
"Button 8" = -
"Button 9"= +
"Button 10" = L3
"Button 11" = R3
