### ISSUE TITLE
SDL Gamepad Support

### ISSUE THREAD

**Issue by dude98** [Venomalia/UniversalDynamicInput#96]
### Input device?

essentially all of them

### Input device ID?

SDL/0/(Insert Controller Name Here) EX: PS5 Controller, Nintendo Switch Pro Controller, Etc.

### Operating System?

Windows 10

### What is the key assignment.

Controller Buttons:
PS5/Switch Pro/Xbox One
`Button 0` = Cross/A/A
`Button 1` = Circle/B/B
`Button 2` = Square/X/X
`Button 3` = Triangle/Y/Y
`Button 4` = Share/Minus/LB
`Button 5` = PS/Home/RB
`Button 6` = Options/Plus/Select
`Button 7` = L3/LS/Start
`Button 8` = R3/RS/LS
`Button 9` = L1/L/RS
`Button 10` = R1/R/Xbox
`Button 11` = Dpad Up (Xbox Doesn't Use This)
`Button 12` = Dpad Down (Xbox Doesn't Use This)
`Button 13` = Dpad Left (Xbox Doesn't Use This)
`Button 14 = Dpad Right (Xbox Doesn't Use This)
`Button 15 = Touchpad/Capture (Xbox Doesn't Use This)
`Button 16` = PS5 Mute Button (Switch Pro And Xbox Don't Have This)
`Hat 0 N` = Xbox Dpad Up
`Hat 0 S` = Xbox Dpad Down
`Hat 0 W` = Xbox Dpad Left
`Hat 0 E` = Xbox Dpad Right
`Full Axis 4+` = L2/ZL/LT
`Full Axis 5+` = R2/ZR/RT
`Axis 0-` = Left Stick Left
`Axis 0+` = Left Stick Right
`Axis 1-` = Left Stick Up
`Axis 1+` = Left Stick Down
`Axis 2-` = Right Stick Left
`Axis 2+` = Right Stick Right
`Axis 3-` = Right Stick Up
`Axis 3+` = Right Stick Down
`Motor` = Controller Rumble
I think that's all the buttons, i'm not putting the motion control stuff down because that's the exact same as the DS4Windows/Betterjoy Stuff.

**Comment by Venomalia** [comment]
how to use the SDL in Windows 10 are they not always called DInput?
I need very accurate input device ID if they do not match exactly it does not work.

**Comment by Venomalia** [comment]
also wen only tested with macOS
SDL/0/PS4 Controller
SDL/0/Xbox Wireless Controller
are technically supported.

Please send me the exact input device IDs of the controllers you have tested.

**Comment by dude98** [comment]
i'm on windows 10.
the input device ids for the three controllers are
SDL/0/PS5 Controller
SDL/0/Switch Pro Controller
SDL/0/Controller (Xbox One For Windows)
